# Welcome to Jekyll!
#

# Site settings
title: Packman
subtitle: An End-to-End Software Packaging Platform
description: > # this means to ignore newlines until "baseurl:"
      An End-to-End Software Packaging Platform;deb;rpm;linux;packages;automation
owner: Packman # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: info@packman.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://packman.io" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/pack-man
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
